name: app_plantas
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
## las dependecias se ordenan por orden alfabetico
  # Navigations
  auto_route: ^7.8.4

  # Blocs
  bloc: ^8.1.4
  # Http
  dio: ^5.4.0
  # Blocs extends
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  
  # UI animations
  flutter_animate: ^4.5.0
  
  # State management
  flutter_bloc: ^8.1.3

  # Environnement of dev
  flutter_dotenv: ^5.1.0

  

  # Internazionalization
  flutter_localizations:
    sdk: flutter

  # Internationalization
  intl: ^0.18.0
  
  # Local Storage
  shared_preferences: ^2.2.2


dev_dependencies:
  # Navegaciones
  auto_route_generator: ^7.3.2

  bloc_test: ^9.1.4

  # archivos auto generados
  build_runner: ^2.4.6
  
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

  

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/
    - stg.env
    - dev.env
    - prod.env
